Approach to support psr15 ^0.4
franzliedke/whoops-middleware pull request #7
Opened 2017-01-28 11:35 UTC by timtegeler

PR regarding to #6

2017-01-30 21:15 UTC, franzliedke requested changes

2017-01-30 21:15 UTC, franzliedke commented on composer.json
> +        "http-interop/http-middleware": "^0.4.1"
Please don't add this here, as it is optional. Instead, add it to `suggest` and `require-dev` (as we should also add tests?).

2017-01-31 08:26 UTC, timtegeler commented on composer.json
> +        "http-interop/http-middleware": "^0.4.1"
You are absolutely right. I will add it to `suggest` and `require-dev`. Tests are on my list too

2017-01-31 10:32 UTC, franzliedke approved these changes

2017-02-01 11:43 UTC, merged

2017-02-01 11:43 UTC, franzliedke commented
Thanks a lot!